const nevekTomb=[
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    },
    {
        "megoldas":"Helyes",
        "tipp1":"Hibás",
        "tipp2":"Hibás",
        "tipp3":"Hibás"
    }

]